version: '3.6'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    volumes:
      - ${STACK_DIR}/config-elasticsearch:/usr/share/elasticsearch/config
      - ${STACK_DIR}/data-elasticsearch:/usr/share/elasticsearch/data
      - ${STACK_DIR}/certs:/usr/share/elasticsearch/config/certs
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    ulimits:
      memlock: -1 # https://www.elastic.co/guide/en/elasticsearch/reference/7.2/setup-configuration-memory.html
      nofile: 65535 # https://www.elastic.co/guide/en/elasticsearch/reference/7.2/file-descriptors.html

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    depends_on:
      - elasticsearch
    volumes:
      - ${STACK_DIR}/config-kibana:/usr/share/kibana/config
      - ${STACK_DIR}/data-kibana:/usr/share/kibana/data
      - ${STACK_DIR}/certs:/usr/share/kibana/config/certs
    ports:
      - ${KIBANA_PORT}:5601
