services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${TAG}
    volumes:
      - ${STACK_DIR}/config-elasticsearch:/usr/share/elasticsearch/config:Z
      - ${STACK_DIR}/logs-elasticsearch:/var/log/elasticsearch:Z
      - ${STACK_DIR}/data-elasticsearch:/var/data/elasticsearch:Z
      - ${STACK_DIR}/certs:/usr/share/elasticsearch/config/certs:z
    env_file: .env
    ports:
      - ${ELASTICSEARCH_PORT}:9200
    restart: on-failure
    ulimits:
      memlock: -1 # https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration-memory.html
      nofile: 65535 # https://www.elastic.co/guide/en/elasticsearch/reference/current/file-descriptors.html
      nproc: 4096 # https://www.elastic.co/guide/en/elasticsearch/reference/current/max-number-of-threads.html

  kibana:
    image: docker.elastic.co/kibana/kibana:${TAG}
    depends_on:
      - elasticsearch
    volumes:
      - ${STACK_DIR}/config-kibana:/usr/share/kibana/config:Z
      - ${STACK_DIR}/data-kibana:/var/data/kibana:Z
      - ${STACK_DIR}/certs:/usr/share/kibana/config/certs:z
    env_file: .env
    ports:
      - ${KIBANA_PORT}:5601
    restart: on-failure
