version: '3.6'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.2.0
    environment:
      - node.name=elasticsearch
    volumes:
      - elasticsearch_config:/usr/share/elasticsearch/config
      - elasticsearch_data:/usr/share/elasticsearch/data
      - certs:/usr/share/elasticsearch/config/certs
    ports:
      - 9200:9200
    ulimits:
      memlock: -1 # https://www.elastic.co/guide/en/elasticsearch/reference/7.2/setup-configuration-memory.html
      nofile: 65535 # https://www.elastic.co/guide/en/elasticsearch/reference/7.2/file-descriptors.html

  start:
    image: dadarek/wait-for-dependencies
    depends_on:
      - elasticsearch
    command: elasticsearch:9200

  setup:
    build: containers/setup
    environment:
      - node.name=elasticsearch
    volumes:
      - elasticsearch_config:/elasticsearch_config
      - elasticsearch_data:/elasticsearch_data
      - certs:/certs
      - passwords:/passwords
      - ${PWD}:/pwd

  curl:
    build: containers/curl
    volumes:
      - certs:/certs
      - passwords:/passwords

volumes:
  elasticsearch_config:
  elasticsearch_data:
  certs:
  passwords:
